CREATE DATABASE IF NOT EXISTS marketplace_db;
CREATE USER 'mk_user'@'%' IDENTIFIED BY 'mk_user123*';
GRANT ALL PRIVILEGES ON marketplace_db.* TO 'mk_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

SHOW DATABASES;