spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://${DB_IP}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PWD}"
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
---
spring:
  config:
    activate:
      on-profile:
        - dev
server:
  port: 9000

---
spring:
  config:
    activate:
      on-profile:
        - test
server:
  port: 8080